### ISSUE TITLE
Sending sleep command via HA or MQTT does not do anything

### ISSUE THREAD

**Issue by dalehumby** [seaky/nspanel_pro_tools_apk#103]
When I send the `sleep` command via MQTT or the HA MQTT integration (press the button on the device in HA) the display does not sleep.

The screen sleeps via the timer (eg after the 15 s or 30 s `Display sleep` time) so it's not that the screen never sleeps. It's just that the sleep command doesn't put the screen to sleep.

In the debug log I can see the sleep command is received. There are not errors in the log.

The `wake` command successfully wakes the screen.

I am running v2.2.0-release

Thanks!

**Comment by seaky** [comment]
I'm on it...

**Comment by seaky** [comment]
i forgot to merge this feature so will be available in v2.2.1 soon

**Comment by dalehumby** [comment]
Thank you so much. Confirmed working in v2.2.1
