### ISSUE TITLE
Unable to connect MQTT with empty User / Password

### ISSUE THREAD

**Issue by onemorename** [seaky/nspanel_pro_tools_apk#105]
I'm unable to connect against my mqtt broker with blank username / password. As soon as i put something in it tries to connect but fails for sure.
Are we only able to connect authenticated here? I think this should be optional

**Comment by seaky** [comment]
Yep, as I tested for anonymous connection you should provide at least a username. Try to provide a fake username wo password. 
Just the hostname and a username is mandatory!

**Comment by onemorename** [comment]
Doesn‘t work, failed to connect with a dummy username and empty password
________________________________
Von: seaky ***@***.***>
Gesendet: Saturday, June 22, 2024 8:47:19 AM
An: seaky/nspanel_pro_tools_apk ***@***.***>
Cc: Martin Aigner ***@***.***>; Author ***@***.***>
Betreff: Re: [seaky/nspanel_pro_tools_apk] Unable to connect MQTT with empty User / Password (Issue #105)


Yep, as I tested for anonymous connection you should provide at least a username. Try to provide a fake username wo password.
Just the hostname and a username is mandatory!

**Comment by seaky** [comment]
will be fixed in 2.2.1 soon

**Comment by seaky** [comment]
new version available

**Comment by onemorename** [comment]
Thanks, this was quick!
Still, it's unable to connect showing 'failed to connect'. I have several other devices connected to the broker without any issue, any idea what may be the reason here?

**Comment by seaky** [comment]
Could you please enable full verbose log and post here?
 You can find the file 
`/data/data/com.seaky.nspanelpro.tools/logs/debug.log`

**Comment by onemorename** [comment]
Was unable to download the file, still sorting out how to get this downloaded:

C:\tools\platform-tools>adb pull /data/data/com.seaky.nspanelpro.tools/logs/debug.log
adb: error: failed to stat remote object '/data/data/com.seaky.nspanelpro.tools/logs/debug.log': Permission denied

When i look on the nspanel log viewer i can see following events / errors:

![processed-19267C4E-D181-4F7E-936E-45AE77887529](https://github.com/seaky/nspanel_pro_tools_apk/assets/111492172/54d212b5-7743-4346-b430-3bd30f78b9a5)
