### ISSUE TITLE
Screen-on begin issues

### ISSUE THREAD

**Issue by bambucha3** [seaky/nspanel_pro_tools_apk#122]
Installed 2 nspanel pros, with firmware v3.30. Everything worked perfectly following the guide.
I have been able to run home assistant app out of the box, without updating webview.

I have been having issues with screen on settings though, I might be doing something wrong.
Current settings: 15sec display sleep, screen-on time ON, weekdays 7am-10pm, weekends 7am-10pm.
What I would like: 7am-10am screen always on, after 10pm it should revert to 15sec display sleep and when i wave, screen would turn on for 15sec. 

Currently what happens is:
A) 15sec display sleep
- First time I set the settings, the screen always turned completely off after 15sec.
- Next day, using the settings above, in the morning the screen became dim (0% brightness), it was always on, but only turned to full brightness after i touched the screen. It returned back to 0% brightness after 15sec. (this feels like the dim after 15sec setting was set)

B) Display never sleep
- If i have the screen set to never sleep, it is always on no matter what. 

Am i doing something wrong? 
I am suspecting there is a bug somewhere with screen on begin code.

Btw, great tool! Everything else works perfectly on first try :)
Will definitely buy you some coffee :)

**Comment by seaky** [comment]
Hi,

Does dim means reduced brightness or fully black in your context?

**Comment by bambucha3** [comment]
I see.
It would be really cool to fully turn off the screen or have it full brightness.
A toggle to remove dimming would be perfect!

**Comment by ViperRNMC** [comment]
I have also an issue with on screen and display sleep display off. In the on screen time the display dims and turn of with the interval from display sleep. Screen turn quickly on after turn off

**Comment by mheimlich** [comment]
Hi

> if you want I can add a switch not to dim the screen.

Yes, please add this switch. I would also like the display to not dim at all during the always on phases.
Thanks for the great app!

**Comment by seaky** [comment]
done in v2.2.3
