### ISSUE TITLE
3.3.0 NS panel pro OTA FW

### ISSUE THREAD

**Issue by saso-g1** [seaky/nspanel_pro_tools_apk#127]
Any chance to add it to repository ?

**Comment by seaky** [comment]
There is NO 3.3.0 fw!

The current versions are:
apk: 3.3.0
fw: 3.0.0

**Comment by saso-g1** [comment]
Thanks a lot gor your answer!

V čet., 1. avg. 2024 23:13 je oseba seaky ***@***.***>
napisala:
