### ISSUE TITLE
Feature request: Dim to bright wake up and Dim disable option

### ISSUE THREAD

**Issue by ennezetalab** [seaky/nspanel_pro_tools_apk#128]
Hi! Would be great to the screen change from Dim to Bright when proximity sensor detect a hand wave (like automagic do). 
In addition: is it possible to disable the Dim phase before display sleep, I mean passing from bright to screen off without intermediate Dim phase.

Thanks a lot!
Giulio

**Comment by seaky** [comment]
Hi,
The first idea is currently available. 
- Change Display sleep mode to Screen dim.
- Enable wake on wave

Regarding the second request. Android Oreo does not allow to override screen off flow: bright->dim->off.
