### ISSUE TITLE
Wake On Wave not working after reboot - V2.2.1

### ISSUE THREAD

**Issue by rb0135** [seaky/nspanel_pro_tools_apk#135]
Hi All,

I upgraded from 2.0 to 2.2.1 recently and have come to find that Wake on Wave doesnt work after each reboot. Use to work perfectly before.

What I discovered was that after the reboot, I went into settings and found although Wake On Wave was turned on, the device would not wake up with the wave. After investigating, i found if I turned the option off, then on again, it would work perfectly until the next reboot of the device.

Tinking out aloud, it seems that although the option is on, maybe in this version (and now i have seen a new version out) the config isnt being loaded corretly (or even though the option is on, in code behind it isnt) on reboot...

Any ideas?

Happy to supply any logs if needed (just let me know how to grab them).. 

Thanks.

**Comment by seaky** [comment]
If you mean 2.2.1 NPP app, then have you tried the version 2.2.2?

**Comment by rb0135** [comment]
Yep, using your app (presming this was in it the Issues section of your App)..

After posting, I did load the V2.2.2 and it has the same issue.

So, after reboot, the only way Wave to Wake works is if I go into the settings, turn the option off, then on even though the option is showing on when rebooted.

I can touch the screen to wake it when Wave to Wake isnt working.

Thanks.

**Comment by seaky** [comment]
Strange I've just reverted back to v2.2.2 on one of my panel and it apparently works.

My test flow is the following:
- uninstall app
- install v2.2.2
- configure on sensor tab the trigger threshold
- turn on Wake-on-wave
- turn on Resume-on-reboot
- check Display-sleep-time value for me it is 15sec
- chekc Display-sleep-mode should set to Screen-off
- wait for sleep, check wake up
- restart 
- wait for sleep, check wake up


could you please try it out?

**Comment by rb0135** [comment]
Thanks for the reply. I had little time today, but tried to run through your steps.

When trying to remove the app, I am getting this error: Failure [DELETE_FAILED_DEVICE_POLICY_MANAGER]

Yes, I stopped the apps running on the device.

I havent had the time to figure out the issue yet, but will get around to trying what you have above.

**Comment by rb0135** [comment]
> Thanks for the reply. I had little time today, but tried to run through your steps.
> 
> When trying to remove the app, I am getting this error: Failure [DELETE_FAILED_DEVICE_POLICY_MANAGER]
> 
> Yes, I stopped the apps running on the device.
> 
> I tried commands using adb uninstall and in the shell, such as: pm uninstall --user 0 com.seaky.nspanelpro.tools pm uninstall com.seaky.nspanelpro.tools adb uninstall com.seaky.nspanelpro.tools
> 
> I havent had the time to figure out the issue yet, but will get around to trying what you have above.

For anyone following, I found the issue. in Settings->Security->Device Admin Apps it had nspanelpro tools listed. Unchecked that and was able to uninstall.

**Comment by rb0135** [comment]
> Strange I've just reverted back to v2.2.2 on one of my panel and it apparently works.
> 
> My test flow is the following:
> 
> * uninstall app
> * install v2.2.2
> * configure on sensor tab the trigger threshold
> * turn on Wake-on-wave
> * turn on Resume-on-reboot
> * check Display-sleep-time value for me it is 15sec
> * chekc Display-sleep-mode should set to Screen-off
> * wait for sleep, check wake up
> * restart
> * wait for sleep, check wake up
> 
> could you please try it out?

Ok, I managed to get through all steps and it is working fine now with the reinstall. There must have been some corruption somewhere.

Thanks, Rob
