### ISSUE TITLE
[Question| How to play audio via HA integration

### ISSUE THREAD

**Issue by EddyK69** [seaky/nspanel_pro_tools_apk#140]
As mentioned in the documentation, is should be possible to play audio files via the HA integration (MQTT)

```
Command topic (v2.2)

- reboot device
- sleep
- wake_up
- play custom audio

```

How can I do that? What command and payload should I send to the MQTT-broker?

**Comment by seaky** [comment]
Sorry, not yet supported. I have not finished this yet
