### ISSUE TITLE
Pro Tools keep crashing on tap after screen off

### ISSUE THREAD

**Issue by smuliv** [seaky/nspanel_pro_tools_apk#143]
Hi, when just waving the display turns on without any problem.
When tapping the nspanel tools crash and have to be started again.

Firmware: 3.1.0, nspanel tools 2.2.3
Deactivated all in "wake on gestures", also deactivated wake on wave - nothing helps.

Kind regards

**Comment by seaky** [comment]
> Hi, when just waving the display turns on without any problem.
> 
> When tapping the nspanel tools crash and have to be started again.
> 
> 
> 
> Firmware: 3.1.0, nspanel tools 2.2.3
> 
> Deactivated all in "wake on gestures", also deactivated wake on wave - nothing helps.
> 
> 
> 
> Kind regards

Do you have any log?

**Comment by smuliv** [comment]
09-30 14:30:50.433 23436 23436 D AndroidRuntime: Shutting down VM
--------- beginning of crash
09-30 14:30:50.433 23436 23436 E AndroidRuntime: FATAL EXCEPTION: main
09-30 14:30:50.433 23436 23436 E AndroidRuntime: Process: com.seaky.nspanelpro.tools, PID: 23436
09-30 14:30:50.433 23436 23436 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.SoundPool.play(int, float, float, int, int, float)' on a null object reference
09-30 14:30:50.433 23436 23436 E AndroidRuntime:        at q0.t$a.a(Unknown Source:14)
09-30 14:30:50.433 23436 23436 E AndroidRuntime:        at z0.a.handleMessage(Unknown Source:19)
09-30 14:30:50.433 23436 23436 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
09-30 14:30:50.433 23436 23436 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
09-30 14:30:50.433 23436 23436 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
09-30 14:30:50.433 23436 23436 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-30 14:30:50.433 23436 23436 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
09-30 14:30:50.433 23436 23436 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by seaky** [comment]
It is a bug! I'll fix it!

**Comment by seaky** [comment]
Workaround turn on audiofeedback then active off-on, turn off audiofeedback

**Comment by seaky** [comment]
or turn off wake-on-touch on 3.10 it works without the app and tap gestures arent supported above 1.10 anyway

**Comment by smuliv** [comment]
I have no wake-on-touch active, because of the warning with 1.10
It's waking up from the system.

**Comment by smuliv** [comment]
Thank you

**Comment by seaky** [comment]
fixed
