### ISSUE TITLE
Question regarding proximity values on version 3.5

### ISSUE THREAD

**Issue by seaky** [seaky/nspanel_pro_tools_apk#144]
Has anyone already updated np86p to 3.5 fw?

Do the proximity sensor values still respond to distance? Or does it only show 0 and 1 now?

thanks in advance

**Comment by seaky** [comment]
if nobody did I strongly suggest NOT to DO!

What I found in kernel they changed the proximity drives so after install you will lose the ability to change proximity distance!!
It is a kernel level change so I cant override!

**Comment by FRConceicao** [comment]
Hello @seaky,

First of all, a big thank you for the app.
Just bought one unit to try it, and unfortunately I did upgrade to latest version (APP: 3.5.3, OS 3.0.0).
The proximity sensor constant triggered at -1.

**Comment by seaky** [comment]
What is your OS version? Is this still 3.0.0?

**Comment by seaky** [comment]
btw Is it an nspanel 86 pro?

**Comment by FRConceicao** [comment]
Hi seaky,

Yes and yes

- NSPeanel Pro 86 
- APP: 3.5.3,  OS 3.0.0

**Comment by seaky** [comment]
It sounds bad, the OS3.0.0 has the original proximity driver so on sensor page you should see that the proximity values are changing according to distance in front of the display. 

Could you enable debug and verbose log? Please select sensor tab and copy logs here just to check.

**Comment by FRConceicao** [comment]
Hi @seaky,

I just disassembled the device and guess what was disconnected?
Now I get the same Proximity and light value range as seen on your screenshot.
Many thanks for all your help.
If you still need logs or anything, from a 86p device let me know, I´ll be more than happy to help on your wonderful project.

**Comment by seaky** [comment]
fixed
