### ISSUE TITLE
Proximity Live Value on firmware 1.5.4

### ISSUE THREAD

**Issue by Bigmanekb** [seaky/nspanel_pro_tools_apk#15]
I have strange values in the proximity live value field.
At the same time, the numbers does not change depending on the distance of the object to the panel
![изображение](https://user-images.githubusercontent.com/46221443/227564520-7a330843-8311-4465-bd76-cccf6c3882d7.png)

Panel firmware is 1.5.4
Accordingly, the automatic switching on of the screen does not work as it should

**Comment by Shamshala** [comment]
Have you ever solved this issue? I don't encounter this issue myself but I would try to dissasemble it and check whether the sensor in the middle is properly seated.

**Comment by Shamshala** [comment]
Have you ever solved this issue? I didn't encounter this myself but I would try to dissasemble it and check whether the sensor in the middle is properly seated.

**Comment by Bigmanekb** [comment]
Nope :(

There is no protective film. I checked twice :) 

At the same time, the readings were the same from the very first launch.

I disassembled the device, all cables are intact

**Comment by SGXander** [comment]
I have high values on one of mine. Not a problem but they are unstable too. I think in my case it's more to do with the mount being close to a corner and it picking up the wall

**Comment by Bigmanekb** [comment]
I haven't disassembled the panel to this extent. The maximum I got to the usb port

**Comment by Bigmanekb** [comment]
> I have high values on one of mine. Not a problem but they are unstable too. I think in my case it's more to do with the mount being close to a corner and it picking up the wall

I have it on my desk. At an angle. Nothing is blocking the view. Values are unstable

**Comment by seaky** [comment]
Does the high value cause any issue or does it standing still? 

Normally the high value souldn’t be an issue the relative change is important.

I have one with ~1000 wo cover and the other has aprox ~4000 as resting value.

btw as I wrote the new version has a bug where the “triggered” label is remained on the screen. You should change between the tabs to fix it.

**Comment by Bigmanekb** [comment]
it's unstable... that's a problem
that is why it is impossible to use the data to regulate the screen on

**Comment by seaky** [comment]
If you mean that the baseline is always different or jumping without any obstacle its pointing to a faulty sensor.

If just the baseline would have been different I could have manage it. :(

**Comment by Bigmanekb** [comment]
One of my assumptions was about the sensor malfunction

**Comment by seaky** [comment]
There is an option to calibrate your faulty proximity sensor. 
I have not played with that but there is a factory test app on the device and there is calibrate menu maybe it can help.
Use google translate :) because it is in chinese

**Comment by Bigmanekb** [comment]
This is the first thing I tried to do, it didn't help
