### ISSUE TITLE
When the device enters sleep mode, it cannot reconnect to the disconnected WiFi.

### ISSUE THREAD

**Issue by maodun96** [seaky/nspanel_pro_tools_apk#154]
This is not a software bug, but a hardware issue with my S6E. I’m not sure if the nspanel pro has this problem, but if the hardware is similar, it might also have it.

Let me describe the issue:

When the device is in sleep mode, the WiFi disconnects (wireless router restarts). In sleep mode, the device does not reconnect to the WiFi. At this point, I need to manually wake the device, and once the screen lights up, the WiFi will reconnect.

The WiFi disconnection causes the Zigbee gateway and switches to become non-functional. Since your future development includes Zigbee, I believe this issue may have some impact.

Could you develop some new features to avoid this problem, such as waking the device when the WiFi disconnects until the WiFi connection is restored?

**Comment by seaky** [comment]
Yep, I've done with that. Will be available on v2.3 soon...

btw, nice catch. I noticed that the devices sometimes drops the connection but I didn't think it was related to me restarting the wifi!

**Comment by maodun96** [comment]
> Yep, I've done with that. Will be available on v2.3 soon...
> 
> btw, nice catch. I noticed that the devices sometimes drops the connection but I didn't think it was related to me restarting the wifi!

Yes, I have also noticed the situation you mentioned. A friend of mine has other brands of panels with this issue occurring very frequently.

I suspect it's due to a mismatch between the hardware and the WiFi settings. I recommended that he use the 802.11N mode, 20MHz bandwidth, WPA-PSK/WPA2-PSK encryption, and TKIP/AES encryption algorithms.

In fact, this is the most common WiFi setting for the 2.4G band in China. It has resolved some connection issues with my other smart devices. Perhaps you could give it a try.

**Comment by maodun96** [comment]
> Yep, I've done with that. Will be available on v2.3 soon...
> 
> btw, nice catch. I noticed that the devices sometimes drops the connection but I didn't think it was related to me restarting the wifi!

After testing version 2.3.1, the S6E-related functions are operating normally.

In sleep mode, the device wakes up after the WiFi is disconnected, and it reconnects to WiFi successfully.
