### ISSUE TITLE
Feature request: Force turn off screen

### ISSUE THREAD

**Issue by ivanroberto** [seaky/nspanel_pro_tools_apk#16]
Hi, in my dashboard I'm using webrtc video from my front door camera, the problem is when the video is showing on the screen the sleep never is triggering.
There is a possibility to force the screen to go to sleep after some time when the proximity sensor is not triggering even with video stream on the screen?
Thanks

**Comment by jjprz** [comment]
Same here. The screen never turn off.

**Comment by seaky** [comment]
First: Check System -> Developer -> Stay awake option
Next: Hmm I'll think it over
