### ISSUE TITLE
Screen keeps turning off and on

### ISSUE THREAD

**Issue by jjprz** [seaky/nspanel_pro_tools_apk#19]
Screen constantly turns off and on when no one is around. Anyone with the same problem?
I only use nspanel_pro_tools_apk and the home assistant companion app

**Comment by wrkn4alivn** [comment]
Same issue. My unit came with v1.5.0, I went through the steps to enable dev mode & remote ADB connection. Loaded Ultra Tiny Launcher, Xposed, HA app, and then this apk. 

I enabled wake on touch (not wake on wave), and then turned on display sleep in the system settings. Now when the sleep kicks in, the screen turns off for about 1 sec and then comes right back on with no touch. Endless cycle off/on. Happy to troubleshoot & provide data if anyone has ideas on what to try next.

**Comment by wrkn4alivn** [comment]
I got a second unit, has all the exact same OS and app versions, but works like a charm. Perhaps some NSPanels have a hardware issue: I notice that my trouble unit reports a fully pegged proximity live value (46200+) regardless of how close anything is to it. Normal should be 20-5000. Even though I'm not using wake-on-wave, it might be related.

(Not sure if there is a way to see/log whether a phantom touch event is happening)

@jjprz What is your proximity live value range?

**Comment by seaky** [comment]
If its still an issue try to disassemble the unit an check the sensor position and the cable

**Comment by seaky** [comment]
after almost a year I close this
