### ISSUE TITLE
Suggested: instructions to enable display sleep

### ISSUE THREAD

**Issue by gdgib** [seaky/nspanel_pro_tools_apk#2]
For those of us trying to avoid reading through all the details of https://blakadder.com/android-panel-proximity/, it might be a good idea to add a note in the instructions about display sleep. I suggest:

```
This app will turn on the display.  In order to make it turn off when not in use, you may change the display sleep settings (`Settings -> Display -> Advanced -> Sleep`).
```

**Comment by gdgib** [comment]
Oh, and thanks for the app.  It's nice and simple.  Love it.

**Comment by seaky** [comment]
thanks I added to the manual.

I close this.

regards,
seaky
