### ISSUE TITLE
App stops every few days

### ISSUE THREAD

**Issue by evil-dog** [seaky/nspanel_pro_tools_apk#20]
I don't know if this is something with my setup or with the app, but after a few days I'm not able to wake the panel with a wave or by touch. This happens regardless of if the panel is used or left idle.

I have v1.1 of the app installed and setup to wake the panel on wave and touch, and to resume on reboot, and I have the active switch on.

It works fine for a few days but then the panel stops waking when I move my hand in front of it or when I touch the panel. I know the panel isn't frozen or otherwise locked up since I can issue the command `adb shell input keyevent 26` and the screen will wake and everything will work fine.

When I open the NSPanelTools app everything appears just how I configured it. Toggling the active switch off and back on makes the app work again for another few days.

I've configured the panel using the guides available at blakadder.com. I've uninstalled the apps listed in one of the articles as being safe to do so. I've installed Ultra Small Launcher, J Touch, Xposed and the updated WebView, NSPanelTools, Speedch Services by Google, and Fake GPS app.

Three things I do beyond the articles is 1) install my self-signed CA root cert, 2) set the hostname by editing the `/vendor/build.prop` file, and 3) install the Home Assistant app.

Is there anything I can provide the next time this happens that would be helpful in debugging?  `adb logcat` perhaps?

**Comment by udivankin** [comment]
Same here. Is there a debug log to refer to?

**Comment by seaky** [comment]
I have an idea that i have to validate. If the OS needs some resources (memory) it reserves the right itself to stop long-running processes.  I have to dig into it.

the log file could be helpful it is in somewhere in the /data/…/nspaneltools folder i dont know by heart

**Comment by seaky** [comment]
A possible fix will be implemented in the new version

**Comment by seaky** [comment]
I found that "the battery optimization" can kill the background processes occasionally

**Comment by seaky** [comment]
probably will be fixed in v2.0

**Comment by seaky** [comment]
Hopefully it has been fixed in v2.0, raise a new issue if it appears again
