### ISSUE TITLE
Feature Request: HA integration service to wake screen

### ISSUE THREAD

**Issue by SGXander** [seaky/nspanel_pro_tools_apk#21]
for when HA integration is completed I'd love to have a service call to wake the screen remotely. currently with fullykiosk there is a delay when the screen wakes while it reconnects to the HA page so it'd be great to use the room occupancy sensor for example to activate the screen in advance.
similarly remote setting of sleep time etc would be useful.

**Comment by jeroenvdd** [comment]
yep I'd like this too :)

**Comment by SGXander** [comment]
In the meantime I've just discovered you can use this:

https://www.home-assistant.io/integrations/androidtv/

Along with the service androidtv.adb_command and the payload POWER will wake the panel remotely. A bit hacky and it takes a few seconds to respond but it works.

**Comment by seaky** [comment]
tons of HA possibilities will be implemented in v2.1

**Comment by seaky** [comment]
available in v2.2.0

**Comment by jeroenvdd** [comment]
ps -> works perfectly far better response vs old 'tv' way
