### ISSUE TITLE
Feature Request: Emulate Home Button

### ISSUE THREAD

**Issue by mikeseeh** [seaky/nspanel_pro_tools_apk#23]
Thanks for this great utility. It makes the NSPanel Pro finally usable. I would be great to have some kind of gesture for emulating the Home button. Currently I use "adb shell input keyevent 3" but some click sequence or waving would avoid opening up the console and connecting to the device. Thanks!

**Comment by seaky** [comment]
Do you have the Display -> show status bar enabled?

**Comment by ScumbagSteve** [comment]
A "exit app" button could at least be integrated in the user interfaces. This would reduce the necessity to send adb keypress commands greatly and I guess it's a quick fix.

**Comment by seaky** [comment]
Will be on 2.1

**Comment by seaky** [comment]
available in v2.2.0
