### ISSUE TITLE
Source code so I can contribute?

### ISSUE THREAD

**Issue by Nerih** [seaky/nspanel_pro_tools_apk#24]
Hi, there are three features i would like to help implement, 1 of which is on the roadmap.

1. Auto Brightness Adjustment - user fine tuning
2. Add proximity option for brightness 
3. Add night mode, leveraging standard existing proximity screen-off and wake for use with 2.

is it possible to publish the source code so i can assist?

**Comment by NdR91** [comment]
A very cool feature might be the possibility to share the proximity and brightness values via MQTT.
This open a bunch of possibilities, for example use this device as a PIR to trigger other actions...

**Comment by seaky** [comment]
Will be implemented in 2.0 soon

**Comment by seaky** [comment]
The app has some reveverse engineered solution which could break EULA if i release it i'd release something proprietary and i dont want to fight with jurists.
