### ISSUE TITLE
Panel goes offline when sleeping

### ISSUE THREAD

**Issue by BenSBB** [seaky/nspanel_pro_tools_apk#26]
I have nspanel tools installed on a T6E panel (basically the same hardware as Sonoff NSPanel)

The wake/touch to wake and other features work great, no problems at all

The problem I have is after some time my panel seems to fully go to sleep - at least it drops off the network (my monitoring tool can no longer ping it)

When the panel is then woken from sleep, it takes some time for my Home Assistant dashboard to work again, I have to wait for the message "disconnected from home assistant" or click the refresh button

I have worked around this by going to developer options and setting the screen to never turn off - obviously this is not desirable when you want to wake the panel using the sensor.

My question - is it possible to just switch off the screen, rather than totally sleep the panel?

**Comment by seaky** [comment]
wait for new version and if it still present, we should check it togheter

**Comment by seaky** [comment]
have you checked it?
