### ISSUE TITLE
Feature request: Touch screen 1sec -> trigger action

### ISSUE THREAD

**Issue by moostmartijn** [seaky/nspanel_pro_tools_apk#27]
It looks like this apk is not under active development anymore, but I'll give it a try.

It would be nice to have an action when touching the screen for 1 sec (hold) without waking the screen. 

Could be HA automation or something like a custom http request so you could toggle the lights in the room without waking the screen by just touching the screen for 1 second.

**Comment by seaky** [comment]
I'll put it on my list

**Comment by seaky** [comment]
Touch gestures will be implemented in 2.1
