### ISSUE TITLE
Resume on reboot button not visible

### ISSUE THREAD

**Issue by Jurian15** [seaky/nspanel_pro_tools_apk#28]
I changed the screen size and font size settings before installing the NSPanelTools, however the content of the wakeup tab are to big when the aforementioned settings are set to large and the 'resume on reboot' button goes off the screen.
Can you make that tab scrollable so all settings are accessible regardless of the size settings?

**Comment by seaky** [comment]
next version will solve this issue

**Comment by seaky** [comment]
fixed in v.2.0.0
