### ISSUE TITLE
Add documentation / summary of project

### ISSUE THREAD

**Issue by ScumbagSteve** [seaky/nspanel_pro_tools_apk#38]
I just stepped over this interesting project and I took a very long time to identify what this is actually about. 
If I understood correctly, you develop an apk that can be installed on NSPanel pro / T6E variants to offer different kinds of functionality, that are useful when running it with the non-standard app. 

I think this should be documented on the top of the page, as well as a short feature list of the app, so people can get an idea if this actually solves their existing problems.

**Comment by seaky** [comment]
thanks and your point taken and I've just changed the doc

**Comment by ScumbagSteve** [comment]
Great thanks. I just read it and one open question that remains is, weather this app also offers a Browser, or not (as this is the most obvious issue to solve for HA integration). You can also drop ioBroker as a keyword. It's more popular in Germany than HA. 

I assume this app is meant to be used in combination with browsers like FullyKiosk, but this could be pointed out.

**Comment by seaky** [comment]
My intention was or is to use this app with HA companion app or other native apps. Although you can try apps as well but the hardware is not a workhorse not even a donkey so it's quite limited.
If you want to install apps which requires moder webui like HA companion or openhab you should upgrade the out-of-the box webview component (see https://github.com/seaky/nspanel_pro_tools_apk?tab=readme-ov-file#install-custom-webview)

I tried the fullykiosk but this is a cannon to kill a mosquito so I wasn't lucky but maybe others will solve the issues around fullykiosk.

**Comment by seaky** [comment]
> Great thanks. I just read it and one open question that remains is, weather this app also offers a Browser, or not (as this is the most obvious issue to solve for HA integration). You can also drop ioBroker as a keyword. It's more popular in Germany than HA.
> 
> I assume this app is meant to be used in combination with browsers like FullyKiosk, but this could be pointed out.

regarding to HA. My plan is to integrate this device into HA vi MQTT as a sensor and switch device therefore the possibilities are endless

**Comment by ScumbagSteve** [comment]
I know about the webview issue, thanks for the heads up. I just received my unit today and it had webview 1007.0.5304.105 installed out of the box. 

In the ewelink app there is even a browser function now, it was labeled as "new" however. I guess that's where it comes from. 

Do you have a recommendation for a lightweight browser by any chance?

**Comment by seaky** [comment]
I'm digging into webview integration so maybe your idea to integrate browser functionallity, will be in v2.3
