### ISSUE TITLE
"Exit app" button

### ISSUE THREAD

**Issue by ScumbagSteve** [seaky/nspanel_pro_tools_apk#46]
An "exit app" button would be great, as it would remove the necessity to send adb commands after changing configuration.

**Comment by seaky** [comment]
will be implemented in v2.1 in a slightly different way

**Comment by seaky** [comment]
fixed in 2.0.1 just released

**Comment by jeroenvdd** [comment]
Don't know if this fits here but exiting 'every' app by swiping or any paterned movement would be nice to exit HA too

**Comment by seaky** [comment]
It is already in the v2.1 called "home as gesture"
