### ISSUE TITLE
Restart app after reboot does not work

### ISSUE THREAD

**Issue by DeCodeerHeer** [seaky/nspanel_pro_tools_apk#49]
When rebooting the device by either an ADB command or cutting the power. The device boots up opening the tools app instead of the app selected. This did work with the previous version. This is happening on both devices now.

I have the option "Resume on boot" turned off and "Launch App after reboot" set on Home Assistant. And I have the "Wait for WiFi" toggle off. Yet, after a fresh start / reboot, it keeps opening the NSPanel Pro tools app instead of the chosen one.

Turning on the "Wait for WiFi" toggle does boot the device to the app. However, for my case the device does not have to wait for WiFi. I just want it to boot to the app directly.

**Comment by seaky** [comment]
It is indeed a bug I will fix it tomorrow in 2.0.1!

**Comment by DeCodeerHeer** [comment]
Alright thanks a bunch!

**Comment by seaky** [comment]
fixed in 2.0.1 just released

**Comment by DeCodeerHeer** [comment]
Works beautifully! Thanks for the fix!
