### ISSUE TITLE
Feature Request: time settings

### ISSUE THREAD

**Issue by LucaBors** [seaky/nspanel_pro_tools_apk#5]
Hi,
first of all thank you for this great project!
If it's possible it would be great if we can set display off time with a timeframe.
Something like. from 8 am to 8 pm leave it on, from 8pm to 8 am turn off display.

Is this something possible?

Thank you! :)

**Comment by seaky** [comment]
Thanks, after I finish the upcoming v1.1 I’ll consider this.

**Comment by jj-uk** [comment]
Yes, i'd like this feature too. If it's possible to set the sleep period in your app instead of in settings-display-advanced-sleep, that would make it slightly easier to configure.

**Comment by seaky** [comment]
Will be implemented in 2.0 soon

**Comment by kroon040** [comment]
Is it possible to have it different on weekdays and weekend?

**Comment by seaky** [comment]
Will be implemented in 2.1

**Comment by seaky** [comment]
> Is it possible to have it different on weekdays and weekend?

Could you please create a separate issue I'd like to label it to 2.1

thx

**Comment by kroon040** [comment]
Made a new issue

**Comment by seaky** [comment]
thanks, close, the original request in the v2.0.0
