### ISSUE TITLE
Feature Request: Activate/Dismiss Screen Saver on Proximity Trigger instead of Sleep/Wake

### ISSUE THREAD

**Issue by kev007** [seaky/nspanel_pro_tools_apk#52]
I found a cool clock app that the native screen saver function activates on the display timeout, but unfortunately, the proximity wake trigger does not dismiss the screen saver. I assume this is because the device counts as awake when displaying the screen saver.

Could you please add a toggle to swap out the sleep/wake actions with activate/dismiss screen saver actions?

**Comment by seaky** [comment]
Could you share the screensaver app name?

I have to check how it is implemented!

Generelly the screensavers overrides the native sleep/awake activities and holds the wakelock. Means being placed a window top of everything by screensaver responsible for dismiss it after touch. Thus not as easy as it looks to dismiss the screensaver.

**Comment by kev007** [comment]
It's this one: https://github.com/schorschii/FsClock-Android
I think this may be the API in use: https://developer.android.com/reference/android/service/dreams/DreamService 
See: https://github.com/schorschii/FsClock-Android/blob/97730f8066767971ae400cd76ad170a71d2697cc/app/src/main/java/systems/sieber/fsclock/FullscreenDream.java#L11

**Comment by seaky** [comment]
I've done a quick check but it looks like the onDreaming state is only reported to that service who is selected the current ScreenSaver... f**k so it needs more investigaton

**Comment by seaky** [comment]
I found a very easy way so I'll try to implement it when I finished the v2.1

**Comment by kev007** [comment]
Nice. Thanks!
