### ISSUE TITLE
Screen-on time Switch with Fully Kiosk Browser

### ISSUE THREAD

**Issue by Patten310** [seaky/nspanel_pro_tools_apk#56]
Screen-on time Switch with Fully Kiosk Browser Is Not working at me. The Display is Not going to sleep. There is no Screensaver activated.

**Comment by seaky** [comment]
Could you please check without fully kiosk is running or deactivated. Fully Kiosk holds tons of wakelocks and can take over the whole sleep control. which prevents to let the device sleep.

Btw my app prevents sleep between screen-on-begin and screen-on-end after that it restores to the original state. Which means will happen which has to be happen :)
