### ISSUE TITLE
Scheduled reboot

### ISSUE THREAD

**Issue by myxlmynx** [seaky/nspanel_pro_tools_apk#57]
After adding ability to reboot panel via application and starting custom application after reboot (with waiting on wifi), please consider adding ability to set periodic reboot e.g. daily/weekly/monthly.
It would help as companion app looks to be troubled with events so sometimes notifications are unable to be delivered and eventually only reboot helps.
Thanks.

**Comment by seaky** [comment]
hi it is relatively simply to implement so it will be on 2.2
I finished the v2.1 and it is under testing so I dont want to bother it now.

**Comment by seaky** [comment]
btw cloud you please share why or how do you use notifications? I've been using HA app for 1.5y and for me the the app some times restart or I have to push the resfresh on screen but thats all. I dont use the notifications (if you mean android push) and I even dont know why it is important.

thx in advance

**Comment by RutgerBeyen** [comment]
Scheduling a reboot is also possible from within HomeAssistant: just fire the relevant ADB commands towards the nspanel by using an automation. This can also avoid  useless reboots, ie only reboot when a certain condition is met.

**Comment by myxlmynx** [comment]
> btw cloud you please share why or how do you use notifications? I've been using HA app for 1.5y and for me the the app some times restart or I have to push the resfresh on screen but thats all. I dont use the notifications (if you mean android push) and I even dont know why it is important.
> 
> thx in advance

Hi and thank *you* in advance for accepting the feature request.

I want to use NSPanel Pro for doorbell functionality in combination with Aqara Smart Button so it alerts when bell button (placed outside besides door) is activated.
Button press is detected fine every time but automation is not able to trigger the notification towards HA companion app running on the panel.
Notification towards my android phone works fine though.

Setting connection persistence for notification delivery to any available option does not seem to have positive effect.

There might be a bug somewhere and in my case it can be helped by either:
- clearing notification history on the panel manually (there are many events from various sensors and integrations), see https://community.home-assistant.io/t/solved-device-not-connected-to-local-push-notifications/476750/
- reboot of panel

As notification history is not something I want to do, I have asked for ability to have panel reboot automated to come out of that misery.
