### ISSUE TITLE
Feature request : Reboot panel

### ISSUE THREAD

**Issue by ianfretwell** [seaky/nspanel_pro_tools_apk#6]
I know this could be done through adb or by loading up the official eWeLink app on the panel - but it would be much simpler to be able to open your app and reboot directly from there.

Hopefully you (and others) agree ?

Thanks.

**Comment by seaky** [comment]
I'm gonna put it to the next version!

**Comment by Corsw** [comment]
This would be even better if we can trigger it from HA. People using pop-ups need to reboot the panel every time HA reboots, else the browser mod cant find the device to send the popup.

Thanks for your effort!

**Comment by seaky** [comment]
> This would be even better if we can trigger it from HA. People using pop-ups need to reboot the panel every time HA reboots, else the browser mod cant find the device to send the popup.
> 
> Thanks for your effort!

Opened a new on with this request.
I close the old. Its in the v2.0.0
