### ISSUE TITLE
HA option is grayed out.

### ISSUE THREAD

**Issue by Klemen1337** [seaky/nspanel_pro_tools_apk#62]
Hi,
I installed v2.0.1 to my NSPanel86PW. Everything works fine but the HA option in the navigation bar is grayed out. Am I missing something?

Cheers,
K

**Comment by ianfretwell** [comment]
Yes, you didn't bother reading the release notes...

It'll be enabled in v2.1.0

**Comment by Klemen1337** [comment]
I see 😄
