### ISSUE TITLE
Feature Request: Screen off when nobody home

### ISSUE THREAD

**Issue by sEdsKi** [seaky/nspanel_pro_tools_apk#66]
If at all possible, a great feature would include having the screen on for a scheduled time, if people are home.

**Comment by seaky** [comment]
for this there are two options currently, 
- schedule a predefinied time period when usually at home (v2.0) 
- use HA integraton to turn screen on/off based on example a human presence sensor (v2.1)

The device itself reliably can not detect human presence. It proximity is for short range, no camera, although it has mic but it think it is not engough.

**Comment by seaky** [comment]
no answer
