### ISSUE TITLE
Don‘t can set Homeassistant

### ISSUE THREAD

**Issue by MaZ181** [seaky/nspanel_pro_tools_apk#69]
Hello i Need Support too aktivate the Homeassistant Integration. I don‘t can tab on den Homeassistant Button. 

What i have too do? 

Thx for Support and Great work with the Tools.apk

![IMG_6684](https://github.com/seaky/nspanel_pro_tools_apk/assets/138328208/a8d88e87-2d3d-4d66-bf00-a6cf34e8c52c)

**Comment by seaky** [comment]
check the documentation: https://github.com/seaky/nspanel_pro_tools_apk?tab=readme-ov-file#app-version-history

HA is not available in v2.0.1 will be available in 2.1 soon

**Comment by seaky** [comment]
2.1 will be release tomorrow

**Comment by MaZ181** [comment]
Thanks
