### ISSUE TITLE
Feature request: Power status

### ISSUE THREAD

**Issue by amaciuc** [seaky/nspanel_pro_tools_apk#7]
Hi,

I saw that there is plan to integrate this app with hassio. I wondered how do you think to do that ?

I am searching a way to monitor the nspanel pro and to design an automation triggered when the nspanel pro is powered off. The integration brought by HA Companion app didn't help much with status of power.

Could you consider this feature? 

Thank you.

**Comment by ianfretwell** [comment]
When you say 'powered off' you just mean as in power is completely removed ?

Strange request for a device that's really meant to be mounted permanently in the wall...so I'm curious of the use case for this ?

**Comment by amaciuc** [comment]
An use case could be when hassio is powered by an UPS and there is an event of power failure, therefore you can shutdown the hassio server if the wall panel is powered off. That also means to know the overall status of panel: shut down, broken.

**Comment by ianfretwell** [comment]
I think that's tenuous at best - if you were doing that sensibly HA would be monitoring the UPS not a wall panel that might be on a different circuit anyway.

**Comment by jj-uk** [comment]
You can auto-shutdown your HA instance by using a UPS integration + automation in HA.

**Comment by amaciuc** [comment]
@ianfretwell 

You can close this issue

I had something in mind but it seems it is not so feasible

**Comment by seaky** [comment]
.

**Comment by seaky** [comment]
close wo action
