### ISSUE TITLE
Feature request : enable access on the IO pin 

### ISSUE THREAD

**Issue by bobzer** [seaky/nspanel_pro_tools_apk#70]
I notice on the image of blakadder that there is 2 pin label IO1 and IO2. I wonder if it will be possible to use them ?
we could plug a relay or a sensor on it ?

![image](https://github.com/seaky/nspanel_pro_tools_apk/assets/2830684/8520a173-134a-414d-9bc3-5853a900125d)

**Comment by seaky** [comment]
Yes u can:
echo 0 > /sys/class/gpio/gpio114/value   - turn off IO1
echo 0 > /sys/class/gpio/gpio115/value   - turn off IO2

echo 1 > /sys/class/gpio/gpio114/value   - turn on IO1
echo 1 > /sys/class/gpio/gpio115/value   - turn on IO2

**Comment by seaky** [comment]
as far as I remember the max gpio load is 10uA

**Comment by bobzer** [comment]
Great thank you, 
Do you know if this is doable through ADB ?
Would be great if it was support in future release, by zigbee or mqtt or other to control it by home assistant 😃 
Thanks again for your wonderfull work

**Comment by seaky** [comment]
adb shell "echo 0 > /sys/class/gpio/gpio114/value"    :sunglasses:

**Comment by seaky** [comment]
planned to v2.2
