### ISSUE TITLE
Feature Request : ethernet support 

### ISSUE THREAD

**Issue by bobzer** [seaky/nspanel_pro_tools_apk#71]
Hi,
Using otg i'm able to plug a usb to ethernet adapter but the settings are stuck at acquiring IP (event if I set a static IP).
Since it's android 8 and there is the ethernet entry in the settings menu ,i guess it should be possible to make it working ?
When I tried with a static ip, the switch can see the device and the connexion but android cannot.
Do you think there is a possibility ?
I love what you do and thank you very much for that

**Comment by seaky** [comment]
I saw your question also at the discussons but i think it is not a common use case.  I personally do not have any experience with this topic.

Btw I'm interested what is the reason or aim to use this device via usb ethernet adapter. It is intended to use as wall device not a fully featured android tablet.

**Comment by bobzer** [comment]
I powered mine by poe, I remove the original power supply and did a super simple cable.
I would love to not be reliant on the wifi, it would be purely ethernet.
got the idea from : https://twitter.com/gralinpl/status/1594737617773498371
but did a simpler easier version :
![image](https://github.com/seaky/nspanel_pro_tools_apk/assets/2830684/f03b68b9-89cb-4a12-a835-0f32013fcbfd)
(not clear in the picture but it's micro usb)
so know i would love to use the otg to have ethernet

**Comment by seaky** [comment]
I can't find any trace of a USB to Ethernet driver in the kernel. So the likelihood of it being resolved is quite small.

**Comment by seaky** [comment]
I take it back I found in the kernel source by default the CONFIG_USB_USBNET=y so the "quite small" is "should work" :D but it depends on the particular binary. 

btw i dont have usb2ether dongle so cant test it sorry

**Comment by bobzer** [comment]
How could I help ?
