### ISSUE TITLE
MQTT client returns not authorised using v2.1.0

### ISSUE THREAD

**Issue by acseven** [seaky/nspanel_pro_tools_apk#75]
Using v2.1.0, I'm not able to connect to the mosquitto server (installed as an addon in HA). I can connect other MQTT clients (i.e. Z2M) in the exact same way and have tried a different user credentials, but it keeps returning "not authorised".

```
2024-03-15 14:01:52: New connection from 10.101.0.165:52954 on port 1883.
2024-03-15 14:01:52: Client nspanelpro17105xxx10847 disconnected, not authorised.
```

Do you have any suggestions?

**Comment by seaky** [comment]
you have to add  a Home Assistant users too, such as mqtt and define pwd as a simple user.
