### ISSUE TITLE
Feature: MQTT commands to turn on screen

### ISSUE THREAD

**Issue by jeroenvdd** [seaky/nspanel_pro_tools_apk#79]
Hi,

I've just installed the new update and it seems to be working i can now see the state trough mqtt.

would it be posssible to have a mqtt input to activate the screen?
thisway i can use the presence detector in HA to activate the Panel,

i do this now via the ADB / android tv integration but it is a tad bit slow,
mqtt might be faster.

Hope you can help! and congrats on the great app again!

**Comment by bobzer** [comment]
You're right, it would be great, it's already disuss there : https://github.com/seaky/nspanel_pro_tools_apk/issues/21
and there https://github.com/seaky/nspanel_pro_tools_apk/discussions/77#discussioncomment-8816359
it's planned for version 2.2
