### ISSUE TITLE
Is my device bricked?

### ISSUE THREAD

**Issue by Klemen1337** [seaky/nspanel_pro_tools_apk#87]
I have no idea where else to ask this so I will ask here.

My device was working fine, but then there was an automatic update I guess. Now my device is stuck in an infinite boot loop. I've tried the factory resert and [Get out from rabbit hole](https://github.com/seaky/nspanel_pro_roottool_apk?tab=readme-ov-file#get-out-from-rabbit-hole) but it doesn't work. The screen just keeps turning on and off

There is a very short glimps of "Installing system update" screen.
![image](https://github.com/seaky/nspanel_pro_tools_apk/assets/6691011/89303390-49ed-4eea-95ad-1a0201d3f180)

Video
https://github.com/seaky/nspanel_pro_tools_apk/assets/6691011/bd57d239-b508-4d81-b259-ffbdfed4c43d

Thanks,
K

**Comment by clfberlin** [comment]
Ok, strange... I've come to the point a few times where I had to use that emergency recovery. What exactly do you see when you cut off power and plug the panel back in? It should show "SONOFF" within a few seconds.

**Comment by seaky** [comment]
Try the following:

- use the following script on your pc (if you have a windows)
```
@ECHO off
echo.
echo Waiting for device…
adb wait-for-device
echo.
adb -d shell stop
```
- connect device via usb to pc

This should freeze your device at a certain point and you have an option to delete the update.zip

**Comment by Klemen1337** [comment]
No luck there. I've tried it both on a macOS and Windows. The command `adb wait-for-device` keeps waiting for the device and never completes.

If i try to execute stop command I get
```bash
~ ❯ adb -d shell stop
/system/bin/sh: stop: not found
```

I do see that the device is in recovery mode
```bash
~ ❯ adb devices -l
List of devices attached
rockchipplatform       recovery 2-1 product:px30_evb model:px30_evb device:px30_evb transport_id:8
```

Here is another video from power up

https://github.com/seaky/nspanel_pro_tools_apk/assets/6691011/30579f81-9dc9-418d-997f-0957fca11f56

**Comment by seaky** [comment]
> ```shell
> ~ ❯ adb -d shell stop
> /system/bin/sh: stop: not found
> ```
Hey is it not a genuine Sonoff device? Am I right? T6E?

Did you try to update a Sonoff OTA to T6E?

Btw 
It looks like the adb is connected, thats fine.

#1
can you run the ```adb -d shell ls``` ?
or can you keep the ```adb -d shell``` connection without drop ?

#2
Alternatively just simply try to run the ``` adb -d reboot```  if it's stuck in recovery and there is not update.zip present; it should kick it out of the loop.

but if you somehow managed to update a Sonoff OTA and it has been updated, hmm, maybe the only way to revive it is through direct flashing.

But before that could you check the ```shell``` command.

**Comment by Klemen1337** [comment]
This is a genuine Sonoff device (NSPanel Pro 86 PW)

No command i tried was found
```
~ ❯ adb -d shell ls
/system/bin/sh: ls: not found
```

---

### I managed to get it unstuck! 😄 
I managed to get into sideload state and got stuck there. So to get out of this state I sideloaded nspanel-pro-tools-2.1.0 again. And it got unstuck!

```
~ ❯ adb reboot sideload
~ ❯ adb sideload nspanel-pro-tools-2.1.0-release.apk
```

Thank you @clfberlin and @seaky for the help! I hope this helps anyone else.

Cheers 🍻 
Klemen

![IMG_5262](https://github.com/seaky/nspanel_pro_tools_apk/assets/6691011/a82e640c-0aaf-4c90-a08e-8197f4718627)
