### ISSUE TITLE
update question

### ISSUE THREAD

**Issue by jeroenvdd** [seaky/nspanel_pro_tools_apk#93]
hi,
U have a small question;
what is the best practice to update the app?

I can't install a new version when the old one is installed, it throws 'app is already installed' trought adb

so i have to do an uninstall / install

is there something I am missing or another way to do it?

**Comment by seaky** [comment]
Hi,
Sometimes reading the manual could be useful. Just search for "Install App" in the manual.😉

Regards

**Comment by jeroenvdd** [comment]
Hi Seaky,
I might be going blind but I can't seem to find a part in that manual about updating the app

**Comment by seaky** [comment]
Look at the Table of Contents, check the 6th item 😉

**Comment by seaky** [comment]
Did you find?
