### ISSUE TITLE
Request to adapt S6E (relay)

### ISSUE THREAD

**Issue by maodun96** [seaky/nspanel_pro_tools_apk#95]
Hello, developer.
I have an S6E device and I really enjoy the programs you've developed, and I'm looking forward to future updates.
As an S6E user, I would like to request a new feature.
The S6E has two relays, and the way to switch them is by writing 0 or 1 to sys/class/gpio/gpio114 (or gpio115)/value.
Would it be possible to implement the use of these relays in the form of a floating window?

The only difference between the S6E and T6E is the relays. So I'm really hoping you can help me with this.

thanks！

Reference links:https://github.com/Astogems/Home-Assistant-S6E-Tuya-Smart-Panel-Relay-Controls

**Comment by seaky** [comment]
Hi,

What does mean "floating window" ?

regards

**Comment by maodun96** [comment]
> Hi,
> 
> What does mean "floating window" ?
> 
> regards

floating button，When using the translator, I introduced Chinese usage habits...
Back on topic, maybe use a floating button to open a menu to control the relay.
When I tried using macrodroid just now, I found that it can add a sidebar to the system. When you slide to open the sidebar, you can run some macros. You can also set some applications to open. Maybe this is also a very good choice.

**Comment by maodun96** [comment]
Hello, @seaky  

I recently tried SoftCircle, which can place widgets created by Automagic on a floating button.
By long pressing, the widgets can be called out, as shown in the image. This almost meets my needs, except that it's quite ugly.
![image](https://github.com/seaky/nspanel_pro_tools_apk/assets/43996175/385962d3-88f0-4733-989c-8e0edee51401)

If possible, I sincerely hope that similar functionality can be integrated into your application. I hope you can consider it. Thank you!

attached the Relay_State script I made with Automagic and the relay switching script modified from the previous link.



<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<data version="1.37.0">
  <trigger type="file_observer">
    <useDefaultName>true</useDefaultName>
    <name>File Observer: /sys/class/gpio/gpio114/value on events Modify</name>
    <enabled>true</enabled>
    <pathList>/sys/class/gpio/gpio114/value</pathList>
    <eventTypeAccess>false</eventTypeAccess>
    <eventTypeAttrib>false</eventTypeAttrib>
    <eventTypeCloseNowrite>false</eventTypeCloseNowrite>
    <eventTypeCloseWrite>false</eventTypeCloseWrite>
    <eventTypeCreate>false</eventTypeCreate>
    <eventTypeDelete>false</eventTypeDelete>
    <eventTypeDeleteSelf>false</eventTypeDeleteSelf>
    <eventTypeModify>true</eventTypeModify>
    <eventTypeMovedFrom>false</eventTypeMovedFrom>
    <eventTypeMovedTo>false</eventTypeMovedTo>
    <eventTypeMoveSelf>false</eventTypeMoveSelf>
    <eventTypeOpen>false</eventTypeOpen>
  </trigger>
  <action type="execute_root_command">
    <useDefaultName>true</useDefaultName>
    <name>Execute Root Command: cat value in /sys/class/gpio/gpio114</name>
    <command>cat value</command>
    <user></user>
    <seContext></seContext>
    <workingDirectory>/sys/class/gpio/gpio114</workingDirectory>
    <timeout>300000</timeout>
    <variableStdout>stdout</variableStdout>
    <variableStderr>stderr</variableStderr>
    <variableExitCode>exit_code</variableExitCode>
  </action>
  <action type="script">
    <useDefaultName>true</useDefaultName>
    <name>Script: if (stdout == "1") { global_relay1_state = "on"; } else { global_relay1_state = "off"; }</name>
    <script>
    if (stdout == "1")
    {
        global_relay1_state = "on";
    }
    else
    {
        global_relay1_state = "off";
    }</script>
  </action>
  <flow type="flow">
    <name>Relay State 1</name>
    <enabled>true</enabled>
    <executionPolicy>PARALLEL</executionPolicy>
    <actioncontainer id="t1" x="175.0" y="122.5">Script: if (stdout == "1") { global_relay1_state = "on"; } else { global_relay1_state = "off"; }</actioncontainer>
    <actioncontainer id="t2" x="35.0" y="-52.5">Execute Root Command: cat value in /sys/class/gpio/gpio114</actioncontainer>
    <triggercontainer id="t3" x="-210.0" y="-17.5">
      <trigger>File Observer: /sys/class/gpio/gpio114/value on events Modify</trigger>
    </triggercontainer>
    <connection from="t2" to="t1" type="NORMAL" sourcePosition="SOUTH" targetPosition="NORTH" />
    <connection from="t3" to="t2" type="NORMAL" sourcePosition="SOUTH" targetPosition="NORTH" />
  </flow>
</data>


<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<data version="1.37.0">
  <trigger type="http_request">
    <useDefaultName>true</useDefaultName>
    <name>HTTP Request: /relay1, port 8080</name>
    <enabled>true</enabled>
    <path>/relay1</path>
    <port>8080</port>
    <bindToWifiOnly>false</bindToWifiOnly>
    <acquireWifiLock>true</acquireWifiLock>
    <finishResponse>false</finishResponse>
  </trigger>
  <action type="execute_root_command">
    <useDefaultName>true</useDefaultName>
    <name>Execute Root Command: echo $(( $(cat /sys/class/gpio/gpio114/value) ^ 1 )) &gt; /sys/class/gpio/gpio114/value in </name>
    <command>echo $(( $(cat /sys/class/gpio/gpio114/value) ^ 1 )) &gt; /sys/class/gpio/gpio114/value</command>
    <user></user>
    <seContext></seContext>
    <workingDirectory></workingDirectory>
    <timeout>300000</timeout>
    <variableStdout>stdout</variableStdout>
    <variableStderr>stderr</variableStderr>
    <variableExitCode>exit_code</variableExitCode>
  </action>
  <flow type="flow">
    <name>Relay 1 toggle</name>
    <enabled>true</enabled>
    <executionPolicy>PARALLEL</executionPolicy>
    <triggercontainer id="t1" x="315.0" y="17.5">
      <trigger>HTTP Request: /relay1, port 8080</trigger>
    </triggercontainer>
    <actioncontainer id="t2" x="315.0" y="262.5">Execute Root Command: echo $(( $(cat /sys/class/gpio/gpio114/value) ^ 1 )) &gt; /sys/class/gpio/gpio114/value in </actioncontainer>
    <connection from="t1" to="t2" type="NORMAL" sourcePosition="SOUTH" targetPosition="NORTH" />
  </flow>
</data>

**Comment by maodun96** [comment]
Please request support for S6E relays in the MQTT service, I have already tried it myself, but I haven't found a very good method. Using HTTP requests + automagic methods, the experience is rather poor. I sincerely request your support. Thank you very much!

**Comment by maodun96** [comment]
I noticed in past issue that you mentioned support for GPIO would be added in version 2.2.0.
This fulfills my need to use HA to control relays. In comparison, the need to operate switches locally on the device is not as important. Because this would only be used in certain emergency situations.

Thank you for the development.

**Comment by seaky** [comment]
the mqtt based switch will be available at 2.2.0 soon

**Comment by maodun96** [comment]
> the mqtt based switch will be available at 2.2.0 soon

Thank you very much for your development.
 I sent an email to your G account. There are some firmware that I can share with you.

**Comment by maodun96** [comment]
@seaky 
Hello, thank you for supporting this feature.
At present, after controlling switch1 and 2 on the device, the status in HA will not change. Can I ask you to support the relevant status feedback?
By the way, I replied to your g email.

regards

**Comment by seaky** [comment]
I leave it open, I’m working on it.

**Comment by maodun96** [comment]
> I leave it open, I’m working on it.

@seaky 
Hello, thank you for your development.

I'm not sure if the relay status feedback feature has been implemented. 

Currently, when I switch the relay locally on the device, the switch status on HA does not update accordingly.
